select distinct
    {{ dbt_utils.generate_surrogate_key(['recipient_profile_id']) }}
        as recipient_key,
    recipient_type,
    teaching_hospital_ccn,
    teaching_hospital_id,
    teaching_hospital_name,
    recipient_profile_id,
    recipient_npi,
    recipient_first_name,
    recipient_middle_name,
    recipient_last_name,
    recipient_name_suffix,
    recipient_address_line_1,
    recipient_address_line_2,
    recipient_city,
    recipient_state,
    recipient_zip_code,
    recipient_country,
    recipient_province,
    recipient_postal_code,
    recipient_type_1,
    recipient_type_2,
    recipient_type_3,
    recipient_type_4,
    recipient_type_5,
    recipient_type_6,
    recipient_specialty_1,
    recipient_specialty_2,
    recipient_specialty_3,
    recipient_specialty_4,
    recipient_specialty_5,
    recipient_specialty_6,
    license_state_1,
    license_state_2,
    license_state_3,
    license_state_4,
    license_state_5
from {{ ref('stg_open_payments') }}